[tool.ruff]

select = ["D", "E", "F", "W", "C", "S", "I", "TCH"]

ignore = []

target-version = "py311"
pydocstyle.convention = "google"
line-length = 100

[tool.coverage.report]
# unit tests fails if the total coverage measurement is under this threshold value
fail_under = 37
