apiVersion: batch/v1
kind: Job
metadata:
  name: ols-client
  namespace: ols-client-test
spec:
  template:
    metadata:
      name: ols-client
    spec:
      serviceAccountName: ols-client-test
      restartPolicy: OnFailure
      containers:
      - name: ols-client
        image: {{ include "client.image" . }}
        command:
        - /bin/sh
        - -c
        - 'curl -v -X POST -s -k -H2 "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer `cat /service-account/token`" -d "{\"query\": \"write a deployment yaml for the mongodb image\"}" https://ols-proxy.ols.svc:8443/ols'
        volumeMounts:
        - name: token-vol
          mountPath: "/service-account"
          readOnly: true
      volumes:
      - name: token-vol
        projected:
          sources:
          - serviceAccountToken:
              audience: ols-proxy.ols.svc
              expirationSeconds: 3600
              path: token
  backoffLimit: 10