apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ols-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ols-rbac-proxy
subjects:
- kind: ServiceAccount
  name: ols-proxy
  namespace: openshift-lightspeed
