apiVersion: v1
kind: Service
metadata:
  labels:
    app: ols-proxy
  name: ols-proxy
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: https
      port: {{ .Values.ols.proxy.containerPorts.https }}
      targetPort: https
  selector:
    app: ols-proxy
