---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ols-proxy
  name: ols-proxy
  namespace: ols
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: ols-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ols-proxy
  namespace: ols
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ols-proxy
  template:
    metadata:
      labels:
        app: ols-proxy
    spec:
      securityContext:
        runAsUser: 65532
      serviceAccountName: ols-proxy
      containers:
      - name: ols-proxy
        image: quay.io/openshift/origin-kube-rbac-proxy:4.14.0
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://0.0.0.0:8080/"
        - "--ignore-paths=/healthz"
        - "--auth-token-audiences=ols-proxy.ols.svc"
        - "--logtostderr=true"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
        securityContext:
          allowPrivilegeEscalation: false
      - name: ols
        image: ${OLS_IMAGE}