apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ include "redis.image" . }}
        ports:
        - name: server
          containerPort: {{ .Values.redis.containerPorts.server }}
        - name: insights
          containerPort: {{ .Values.redis.containerPorts.insights }}