apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: redis-insights
  namespace: {{ .Release.Namespace | quote }}
spec:
  to:
    kind: Service
    name: redis-stack
  port:
    targetPort: {{ .Values.redis.containerPorts.insights }}
  wildcardPolicy: None
