apiVersion: v1
kind: Service
metadata:
  name: redis-stack
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: server
      port: {{ .Values.redis.containerPorts.server }}
      targetPort: server
    - name: insights
      port: {{ .Values.redis.containerPorts.insights }}
      targetPort: insights
